In [3]:
import numpy as np

In [14]:
a = np.random.random((2,4))

In [15]:
print(a)

[[0.82975223 0.42676954 0.42484093 0.45227701]
 [0.53928176 0.98877266 0.31357291 0.65784483]]


In [8]:
np.sum(a)

3.952653805885646

In [9]:
np.min(a)

0.10650269516072275

In [10]:
np.max(a)

0.8844079576815237

In [23]:
np.sum(a,axis = 1) #在行內求總和

array([2.13363972, 2.49947215])

In [19]:
np.max(a,axis = 0)#(在列內求最大值)

array([0.82975223, 0.98877266, 0.42484093, 0.65784483])