In [1]:
import pandas as pd
import numpy as np

In [2]:
array = np.array([[1,2,3,],
                 [2,3,4]])

In [3]:
print(array)

[[1 2 3]
 [2 3 4]]


In [9]:
print('number of dim:',array.ndim)

number of dim: 2


In [6]:
print('shape:',array.shape)

shape: (2, 3)


In [7]:
print('size',array.size)

size 6


In [43]:
a= np.linspace(1,10,6).reshape((2,3))

In [44]:
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [19]:
print(a.dtype)

int8
