In [1]:
import numpy as np

In [2]:
A = np.arange(2,14).reshape((3,4))

In [3]:
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [4]:
print(np.argmin(A)) #索引值內最小的

0


In [5]:
print(np.argmax(A)) #索引值內最大的

11


In [6]:
print(np.mean(A)) #中位數

7.5


In [7]:
print(np.median(A)) #中位數

7.5


In [8]:
print(np.cumsum(A)) #從頭加到尾有點類似 i++的概念(累加)

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [9]:
print(np.diff(A)) #每一個值跟前一個差多少(累差)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
print(np.nonzero(A)) #顯示不是0的位置左邊的陣列是顯示第幾行`,右邊陣列顯示第幾列

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [12]:
A =np.arange(3,15).reshape((3,4)) #在3~15的範圍內給它3行4列

In [13]:
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [17]:
print(A[1][1]) #印出陣列中的 第一行第一列也可以用 print(A[2,1])

8


In [18]:
for column in A.T: #對列進行迭代
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
