In [1]:
import numpy as np

In [2]:
A = np.array([1,1,1])

In [3]:
B = np.array([2,2,2])

In [4]:
C = np.vstack((A,B)) #上下合併

In [22]:
print(C)

[[1 1 1]
 [2 2 2]]


In [6]:
print(A.shape,C.shape) #A只有三列,C有兩行三列

(3,) (2, 3)


In [7]:
D = np.hstack((A,B))#左右合併

In [8]:
print(A.shape,D.shape) #A只有三列,D有六列

(3,) (6,)


In [20]:
print(A[np.newaxis,:])#冒號在後面就變成二維的1行三列

[[1 1 1]]


In [16]:
print(A[np.newaxis,:].shape) 

(1, 3)


In [19]:
print(A[:,np.newaxis])#冒號在前面就變成二維的三行一列

[[1]
 [1]
 [1]]


In [21]:
print(A[:,np.newaxis].shape)

(3, 1)


In [23]:
A = np.array([1,1,1])[:,np.newaxis]

In [24]:
B = np.array([2,2,2])[:,np.newaxis]

In [25]:
D = np.hstack((A,B))#左右合併

In [26]:
print(D) #改變為三行兩列

[[1 2]
 [1 2]
 [1 2]]


In [27]:
C = np.concatenate((A,B,B,A))#在沒指定axis時為0,等於上下合併

In [29]:
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [30]:
C = np.concatenate((A,B,B,A),axis = 1)#指定axis為1時,等於左右合併

In [31]:
print(C)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [32]:
E = ([1,1,1])

In [33]:
F =([2,2,2])

In [34]:
G = E + F

In [35]:
print(G)

[1, 1, 1, 2, 2, 2]
